apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  rabbitmq_host: {{ .Release.Name }}
  rabbitmq.conf: |-
{{ .Files.Get "rabbitmq.conf" | indent 4 }}
